### ISSUE TITLE
Should we add CVE-2019-1301?

### ISSUE THREAD

**Issue by bbossola** [RetireNet/Packages#22]
I am not completely sure if we should add this one, it looks like it has an impact on system management.

https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-1301

What do you think?

**Comment by johnkors** [comment]
Hi!

This is actually a good question. There is a more detailed report here: https://github.com/dotnet/announcements/issues/121

This CVE is concerning a vulnerable runtime. In .NET Core, in general, we cannot tell which runtime an app is running on at build/restore time. The only consistent way to report about insecure runtimes is to hook into the app itself when it's running on a server.

That's why I've added two such possibilities for developers:
* https://github.com/RetireNet/dotnet-retire#retirenetruntimesmiddleware
* https://github.com/RetireNet/dotnet-retire#retirenetruntimesbackgroundservices

We _could_ add the runtime packages as part of the warnings at build time, but they will often be false positives due the roll forward mechanism for the .NET Core runtimes.

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.13/2.1.13.md#cve-2019-1301-denial-of-service-vulnerability-in-net-core

**Comment by johnkors** [comment]
Both affected modules (`System.Net.Sockets` & `Microsoft.NetCore.App` ) are only possible to fix by installing a new runtime on the server.

**Comment by bbossola** [comment]
Thanks a lot, I think I will add them on my side, I'd like to have them also at build time.
