### ISSUE TITLE
The database seems to be stale

### ISSUE THREAD

**Issue by bbossola** [RetireNet/Packages#28]
Is there any plan to maintaining the database? It looks like the last update was done 8 months ago :)

**Comment by johnkors** [comment]
Yes, so with the .NET team moving more functionality into the runtime as opposed to Nugets, I guess this is to be expected. Meaning: security patches are released as runtime patches instead of as packages. To detect use of a vulnerable runtime version, you would have to run the analysis at runtime instead of at build/restore time.

**Comment by johnkors** [comment]
That said, if there is a vulnerable nuget package you feel is missing, please report it here and I'll happily add it!
